# Generated by Django 5.1.3 on 2024-12-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cloth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=4)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
